[package]
name = "lyrebird"
version = "0.1.0"
description = "Music player written in Rust based on libAudio"
license = "BSD-3-Clause"
authors = ["Rachel Mant <git@dragonmux.network>"]
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29"
